package drools.recommendation;

import drools.recommendation.Recommendation;
import drools.recommendation.Recipe;
import drools.recommendation.Ingredient;
import drools.recommendation.User;

import drools.conclusion.EatingUnhealthy;




query "SimpleResults"
  Number($maxHit: intValue) from accumulate(
      Recommendation($hit: hit),
      max($hit)
  )
  $recommendation: Recommendation(hit == $maxHit, hit >= 0)
end

query "Recipes"
    $recipe: Recipe()
end

query "Conclusions"
    $unhealthy: EatingUnhealthy()
end

query "User"
    $user: User()
end

query "Ingredients"
    $ingredients: Ingredient()
end


query "AllRecommendations"
  $recommendation: Recommendation()
end

query "Started"
  $started: StartedEngine()
end