package drools.recommendation;

import drools.recommendation.Recipe;
import drools.recommendation.Recommendation;
import drools.recommendation.User;
import drools.recommendation.Ingredient;
import drools.recommendation.StorageItem;
import java.time.temporal.ChronoUnit;


rule "Expiration ingredients"
    salience 98
    agenda-group "Recommendation"
when
    $user: User($storage: storage)
    $recipe: Recipe($id: id, $rIngredients: ingredients)
    $ingredients: List() from accumulate(
        RecipeIngredient($i: ingredient) from $rIngredients,
        collectList($i)
    )
    $expiration: StorageItem(ingredient memberOf $ingredients, $bestBefore: bestBefore) from $storage
    Number($bestUntil: intValue >= 0 && <= 30) from ChronoUnit.DAYS.between(LocalDate.now(), $bestBefore)
then
    insert(new Recommendation($id, 100 - $bestUntil));
    System.out.printf("Increase hit by %s for recipe '%s'\n", $bestUntil, $recipe.getId());
end