package drools.recommendation;

import drools.recommendation.Recipe;
import drools.recommendation.Ingredient;
import drools.recommendation.IngredientType;
import drools.recommendation.MadeRecipe;
import drools.conclusion.Vegan;
import drools.conclusion.Vegeterian;
import drools.conclusion.OnKetoDiet;


rule "User acts like a vegeterian(90% of made recipes in last month is vegeterian)"
when
    User($id: id)
    Number(doubleValue > 0.9) from accumulate(
        MadeRecipe($p: recipe.vegetarian) from entry-point $history,
        average($p ? 1.0 : 0.0)
    )
then
    System.out.printf("Insert a fact that user %s is vegetarian.\n", $id);
end
