version: '3.7'

services:
  postgres:
    image: postgres:9.6.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recipes
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
